plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
# Forcing rebuild by removing remote_theme temporarily
title: rootðŸ’€the.opemi.aa-sec:~#
description: On a mission to save planet earth! Hack. Eat. Sleep. Repeat.
show_downloads: false
show_repo: false

collections:
  hack:
    output: true
