plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: rootðŸ’€the.opemi.aa-sec:~#
description: On a mission to save planet earth! Hack. Eat. Sleep. Repeat.
show_downloads: false
show_repo: false

excerpt_separator: "<!--more-->"

collections:
  hack:
    output: true
    permalink: /hack/:name.html
